#pragma once

#include <cstdint>
#include <functional>
#include <optional>
#include <string>
#include <vector>

#include "core/account_store/account.hpp"
#include "core/crypto/secure_string.hpp"

namespace sam::steam_login {

enum class GuardKind {
    None = 0,
    DeviceCode = 1,        // generated by Steam Mobile app / our TOTP
    EmailCode = 2,
    DeviceConfirmation = 3, // approve on the Mobile app
    EmailConfirmation = 4,  // click link in email
};

struct BeginSessionResult {
    bool ok = false;
    std::string error;
    std::string client_id;
    std::string request_id;
    std::int64_t interval_seconds = 5;
    std::vector<GuardKind> allowed_confirmations;
    std::uint64_t steam_id = 0;
    std::int64_t weak_token_unix = 0;
};

struct PollResult {
    bool ok = false;
    std::string error;
    bool finished = false;
    crypto::SecureString access_token;
    crypto::SecureString refresh_token;
    std::string new_client_id;  // server sometimes rotates this
    bool needs_guard_input = false;
};

struct MobileLogin {
    std::string username;
    crypto::SecureString password;
    std::string device_friendly_name = "steam-account-manager";
    std::string platform_user_agent;
};

BeginSessionResult begin_session(const MobileLogin& login);

// Submits a Steam Guard code (TOTP from a shared_secret or email code).
bool submit_guard_code(const std::string& client_id,
                        std::uint64_t steam_id,
                        const std::string& code,
                        GuardKind kind,
                        std::string* error_out = nullptr);

PollResult poll_session(const std::string& client_id, const std::string& request_id);

// High-level convenience that runs the full flow. `on_guard_needed` is invoked
// with the allowed guard kinds; it should return the code to submit (or empty
// to fail). `on_status` is invoked with status messages so the UI can show
// progress.
struct FullLoginResult {
    bool ok = false;
    std::string error;
    core::Account account;  // populated on success
};

FullLoginResult run_full_login(
    const MobileLogin& login,
    const std::function<std::string(const std::vector<GuardKind>&)>& on_guard_needed,
    const std::function<void(const std::string&)>& on_status);

// Returns a Steam Guard code: TOTP from the shared_secret if available and the
// server accepts a DeviceCode confirmation; otherwise calls `on_prompt` so the
// caller (UI) can collect the code from the user. Returns an empty string if
// neither path can produce a code.
//
// Requires `time_aligner` to be synced for the TOTP path: codes generated
// against an unsynced clock will be rejected by Steam as
// k_EResult_TwoFactorCodeMismatch (88).
std::string default_guard_provider(
    const std::optional<core::SteamGuardAccount>& sda,
    const std::vector<GuardKind>& allowed,
    const std::function<std::string(const std::vector<GuardKind>&)>& on_prompt);

}  // namespace sam::steam_login
